#!/usr/bin/env bash
# Produce release/images.lock for a product from REAL images.
#
#   make-images-lock.sh --product assessment --version <X.Y.Z> \
#       --template <Assessment checkout>/deployment/v1/release/images.lock.template \
#       --output dist/images.lock [--verify-registry] [--no-pull]
#
# The template lists "name=reference" (never digests); @VERSION@ becomes the
# release version.  For every line this script asks Docker which repository
# digest the image has and writes "name=reference@sha256:<digest>".  A digest is
# never typed in and never guessed: an image without a repository digest (built
# locally and not pushed/pulled yet) stops the script with the command to run.
#
# Run it on a machine with Docker AFTER the first-party images were pushed to
# registry.neosecra.com (the publish host: registry writes are only accepted
# from there).  Public images (postgres, redis, openvas, zap) are pulled here when
# they are missing locally, unless --no-pull is given; the private registry is
# never pulled from.  --verify-registry additionally asks the registry
# (docker manifest inspect) for every digest and fails when it cannot confirm it.
#
# The result is validated with the publisher's own parser (update-server/lib/registry.py).
set -Eeuo pipefail
umask 077
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
PRODUCT="" VERSION="" TEMPLATE="" OUTPUT="" VERIFY=0 PULL=1
PRIVATE_REGISTRY="registry.neosecra.com"

die() { echo "[ERROR] $*" >&2; exit 1; }
usage() { sed -n '2,/^set -Eeuo/p' "${BASH_SOURCE[0]}" | sed '$d' | sed 's/^# \{0,1\}//'; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    --product) PRODUCT="${2:-}"; shift 2 ;;
    --version) VERSION="${2:-}"; shift 2 ;;
    --template) TEMPLATE="${2:-}"; shift 2 ;;
    --output) OUTPUT="${2:-}"; shift 2 ;;
    --verify-registry) VERIFY=1; shift ;;
    --no-pull) PULL=0; shift ;;
    --help|-h) usage; exit 0 ;;
    *) usage >&2; die "unknown option: $1" ;;
  esac
done
[[ -n "$PRODUCT" && -n "$VERSION" && -n "$TEMPLATE" && -n "$OUTPUT" ]] || { usage >&2; die "--product --version --template --output are required"; }
[[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || die "version must be numeric semver X.Y.Z"
[[ -f "$TEMPLATE" && ! -L "$TEMPLATE" ]] || die "template not found: $TEMPLATE"
[[ ! -e "$OUTPUT" ]] || die "refusing to overwrite an existing lock: $OUTPUT"
command -v docker >/dev/null 2>&1 || die "docker is required"
command -v python3 >/dev/null 2>&1 || die "python3 is required"

# Repository part of a reference (tag stripped; a registry port is not a tag).
repository_of() {
  local ref="${1%%@*}" last
  if [[ "$ref" == */* ]]; then last="${ref##*/}"; printf '%s/%s' "${ref%/*}" "${last%%:*}"; else printf '%s' "${ref%%:*}"; fi
}

repo_digest() {  # repo_digest <reference> -> sha256:... of the matching repository digest, or nothing
  local ref="$1" repo entry
  repo="$(repository_of "$ref")"
  while IFS= read -r entry; do
    entry="${entry//$'\r'/}"
    [[ -n "$entry" ]] || continue
    case "${entry%%@*}" in
      "$repo"|"docker.io/${repo}"|"docker.io/library/${repo}"|"index.docker.io/${repo}"|"index.docker.io/library/${repo}")
        printf '%s' "${entry#*@}"; return 0 ;;
    esac
  done < <(docker image inspect --format '{{range .RepoDigests}}{{println .}}{{end}}' "$ref" 2>/dev/null || true)
  return 1
}

TMP="$(mktemp "${OUTPUT}.XXXXXX")"
trap 'rm -f -- "$TMP"' EXIT
{
  echo "# ${PRODUCT} ${VERSION} image lock - generated by update-server/make-images-lock.sh from real images."
  echo "# name=reference@sha256:<repository digest>. Never edit by hand."
} > "$TMP"

while IFS= read -r line || [[ -n "$line" ]]; do
  line="${line//$'\r'/}"
  [[ -n "${line//[[:space:]]/}" && "${line#"${line%%[![:space:]]*}"}" != \#* ]] || continue
  [[ "$line" == *=* ]] || die "invalid template line: $line"
  name="${line%%=*}"; ref="${line#*=}"
  ref="${ref//@VERSION@/$VERSION}"
  [[ "$name" =~ ^[a-z0-9][a-z0-9._-]*$ ]] || die "invalid service name: $name"
  [[ "$ref" != *@* && "$ref" != *":latest" && "$ref" =~ ^[a-z0-9][a-z0-9./:_-]*$ ]] || die "template reference for ${name} must be a lowercase tag reference without digest (got: ${ref})"
  digest=""
  if ! digest="$(repo_digest "$ref")" || [[ -z "$digest" ]]; then
    if [[ "$ref" == "${PRIVATE_REGISTRY}/"* ]]; then
      die "${name}: ${ref} has no repository digest on this machine. Push it first (docker push ${ref}) from the publish host; the private registry is never pulled from here."
    elif [[ $PULL -eq 1 ]]; then
      echo "[INFO] ${name}: pulling public image ${ref}" >&2
      docker pull "$ref" >/dev/null || die "${name}: could not pull ${ref}"
      digest="$(repo_digest "$ref")" || die "${name}: ${ref} still has no repository digest after pulling"
    else
      die "${name}: ${ref} is not present locally (run without --no-pull to pull public images)"
    fi
  fi
  [[ "$digest" =~ ^sha256:[0-9a-f]{64}$ ]] || die "${name}: invalid digest from docker: ${digest}"
  if [[ $VERIFY -eq 1 ]]; then
    docker manifest inspect "$(repository_of "$ref")@${digest}" >/dev/null 2>&1 || die "${name}: the registry does not confirm $(repository_of "$ref")@${digest}"
  fi
  printf '%s=%s@%s\n' "$name" "$ref" "$digest" >> "$TMP"
  echo "[INFO] ${name}: ${ref}@${digest}" >&2
done < "$TEMPLATE"

# The publisher's own validation (service set, shared digests, mutable references).
python3 - "$REPO_ROOT" "$PRODUCT" "$TMP" <<'PY'
import sys
from pathlib import Path
root, product, lock = sys.argv[1:]
sys.path.insert(0, root + '/update-server/lib')
from registry import images, load_registry
try:
    rows = images(lock, load_registry(Path(root), product))
except ValueError as exc:
    raise SystemExit('[ERROR] image lock rejected by the publisher validation: ' + str(exc))
print('[INFO] image lock accepted by the publisher validation: %d images' % len(rows), file=sys.stderr)
PY
mv -- "$TMP" "$OUTPUT"
trap - EXIT
echo "[INFO] wrote ${OUTPUT}" >&2
